import test from 'node:test';
import assert from 'node:assert/strict';
import vm from 'node:vm';
import {readFile} from 'node:fs/promises';
const source=(await readFile(new URL('../src/backend.js',import.meta.url),'utf8')).replaceAll('export ', '');
function setup(){
 const storage=new Map([['gyosoku.session.v1',JSON.stringify({access_token:'old',refresh_token:'refresh',expires_at:Date.now()+3600000})]]);
 let handler=async()=>new Response('[]');const requests=[];
 const context=vm.createContext({URLSearchParams,Date,JSON,Number,Set,Response,localStorage:{getItem:k=>storage.get(k)||null,setItem:(k,v)=>storage.set(k,v),removeItem:k=>storage.delete(k)},location:{hash:'',pathname:'/fisherman/',search:'',origin:'https://example.test'},history:{replaceState(){}},fetch:async(url,options)=>{requests.push({url,options});if(url==='/public/config.json')return Response.json({supabaseUrl:'https://backend.example',supabaseAnonKey:'public-key'});if(url.endsWith('/auth/v1/user'))return Response.json({id:'user-1'});return handler(url,options);}});
 vm.runInContext(source,context);
 return {call:(code)=>vm.runInContext(code,context),requests,storage,setHandler:fn=>handler=fn};
}
test('network failure does not erase session and failed reads/deletes are distinct',async()=>{const b=setup();await b.call('init()');b.setHandler(async()=>{throw Error('offline');});assert.equal(await b.call('listCatches()'),null);assert.equal(await b.call("deleteCatch('report')"),false);assert.ok(b.call('getSession()'));});
test('successful empty cloud list is an array',async()=>{const b=setup();await b.call('init()');assert.equal((await b.call('listCatches()')).length,0);});
test('refresh failure preserves session on temporary server error',async()=>{const b=setup();await b.call('init()');b.call('session.expires_at=0');b.setHandler(async()=>new Response('',{status:503}));assert.equal(await b.call('listCatches()'),null);assert.ok(b.call('getSession()'));});
test('expired refresh token notifies once and removes session',async()=>{const b=setup();await b.call('init()');b.call('globalThis.lost=0; onSessionLost(()=>lost++); session.expires_at=0');b.setHandler(async()=>new Response('',{status:400}));await b.call('listCatches()');await b.call('listCatches()');assert.equal(b.call('lost'),1);assert.equal(b.call('getSession()'),null);});
test('concurrent requests share one refresh and keep user identity',async()=>{const b=setup();await b.call('init()');b.call('session.expires_at=0');let refreshes=0;b.setHandler(async url=>{if(url.includes('/auth/v1/token')){refreshes++;await new Promise(resolve=>setTimeout(resolve,10));return Response.json({access_token:'new',refresh_token:'new-refresh',expires_in:3600});}return Response.json([]);});await Promise.all([b.call('listCatches()'),b.call('listCatches()')]);assert.equal(refreshes,1);assert.equal(b.call('getSession().user.id'),'user-1');});
test('retrying a report uses its existing ID and upsert preference',async()=>{const b=setup();await b.call('init()');b.setHandler(async(url,options)=>Response.json([JSON.parse(options.body)]));const code="saveCatch({id:'same-id',species:'skipjack',quantity:12,date:'2026-10-10',port:'Kesennuma',certainty:'expected'})";await b.call(code);await b.call(code);const posts=b.requests.filter(r=>r.options?.method==='POST');assert.equal(posts.length,2);for(const p of posts){assert.equal(JSON.parse(p.options.body).id,'same-id');assert.match(p.options.headers.Prefer,/resolution=merge-duplicates/);}});
test('sign out while refresh is in flight cannot restore session',async()=>{const b=setup();await b.call('init()');b.call('session.expires_at=0');let respond;b.setHandler(()=>new Promise(resolve=>respond=resolve));const request=b.call('listCatches()');b.call('signOut()');respond(Response.json({access_token:'new',refresh_token:'refresh',expires_in:3600}));await request;assert.equal(b.call('getSession()'),null);});
test('an update affecting no report does not report success',async()=>{const b=setup();await b.call('init()');b.setHandler(async()=>Response.json([]));assert.equal(await b.call("updateCatch('missing',{species:'skipjack',quantity:10,date:'2026-10-10',port:'Kesennuma',certainty:'expected'})"),false);});
test('401 refreshes the token and retries the original request once',async()=>{const b=setup();await b.call('init()');let reads=0;b.setHandler(async url=>{if(url.includes('/auth/v1/token'))return Response.json({access_token:'new',refresh_token:'next',expires_in:3600});reads++;return reads===1?new Response('',{status:401}):Response.json([]);});const rows=await b.call('listCatches()');assert.equal(rows.length,0);assert.equal(reads,2);assert.equal(b.requests.at(-1).options.headers.Authorization,'Bearer new');});
